# Generated by Django 4.1.1 on 2022-09-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='broker_platform',
            field=models.JSONField(default=dict, null=True, verbose_name='Broker Platforms'),
        ),
        migrations.AddField(
            model_name='user',
            name='signal_platform',
            field=models.JSONField(default=dict, null=True, verbose_name='Signal Platforms'),
        ),
    ]
