# Generated by Django 4.1.1 on 2022-09-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_broker_platform_user_signal_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_profile_img',
            field=models.URLField(blank=True, null=True, verbose_name='Profile Image'),
        ),
    ]
